// Code generated by "stringer -type=Language"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C-0]
	_ = x[Cpp-1]
	_ = x[Kotlin-2]
	_ = x[Java-3]
	_ = x[Rust-4]
	_ = x[Go-5]
	_ = x[Odin-6]
	_ = x[CSharp-7]
	_ = x[FSharp-8]
	_ = x[CustomLang-9]
}

const _Language_name = "CCppKotlinJavaRustGoOdinCSharpFSharpCustomLang"

var _Language_index = [...]uint8{0, 1, 4, 10, 14, 18, 20, 24, 30, 36, 46}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
