// Code generated by "stringer -type=Tool"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMake-0]
	_ = x[Nob-1]
	_ = x[Raw_GCC-2]
	_ = x[Raw_MSVC-3]
	_ = x[raw_CLANG-4]
	_ = x[Gradle-5]
	_ = x[raw_KotlinC-6]
	_ = x[raw_JavaC-7]
	_ = x[Meson-8]
	_ = x[Cargo-9]
	_ = x[raw_RustC-10]
	_ = x[Make-11]
	_ = x[Taskfile-12]
	_ = x[GoCmd-13]
	_ = x[OdinCmd-14]
	_ = x[DotNet-15]
}

const _Tool_name = "CMakeNobRaw_GCCRaw_MSVCraw_CLANGGradleraw_KotlinCraw_JavaCMesonCargoraw_RustCMakeTaskfileGoCmdOdinCmdDotNet"

var _Tool_index = [...]uint8{0, 5, 8, 15, 23, 32, 38, 49, 58, 63, 68, 77, 81, 89, 94, 101, 107}

func (i Tool) String() string {
	if i < 0 || i >= Tool(len(_Tool_index)-1) {
		return "Tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tool_name[_Tool_index[i]:_Tool_index[i+1]]
}
